[package]
name = "forsyde-io"
version = "0.3.4"
authors = ["jordao <jordao@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "^0.5.1"
