name:                forsyde-io-haskell
version:             "0.2.12"
github:              "forsyde/forsyde-io"
license:             BSD3
author:              "Rodolfo Jordao"
maintainer:          "jordao@kth.com"
copyright:           "2020 Rodolfo Jordao"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the documentation at <https://forsyde.io.github/forsyde-io>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- hashable >= 1.3.0.0
# - regex-base >= 0.94.0.0
# - regex-tdfa >= 1.3.1.0
- hxt >= 9.3.1
- hxt-xpath >= 9.1.2.1
- split
- bytestring
- algebraic-graphs >= 0.5
- graphite >= 0.10.1.0

library:
  source-dirs: src

executables:
  generate-types:
    main:                Generate.hs
    #source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - unordered-containers
    - text

tests:
  forsyde-io-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forsyde-io-haskell
