name = "ForSyDeIO"
uuid = "2530d2c0-90ae-4e22-bd10-17e782bf2dab"
authors = ["Rodolfo Jordão <jordao@kth.se> and contributors"]
version = "0.3.3"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
