# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name:  Publish ConverSyDe tool

on:
  workflow_dispatch:
  release:
    types: [published]

env:
    MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
    MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
    USERNAME: ${{ github.actor }}
    TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish-conversyde-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Build with Gradle (All)
      # if: ${{ matrix.os != 'windows-latest' }}
      run: |
        cd ${{ github.workspace }}
        ./gradlew jar shadowJar java-conversyde:jpackageImage
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r conversyde.zip ${{ github.workspace }}/java-conversyde/build/jpackage/java-conversyde/*
    - name: Upload Jar to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/java-conversyde/build/libs/conversyde-${{ steps.get_version.outputs.version-without-v }}-all.jar
        asset_name: conversyde-all-cli-${{ steps.get_version.outputs.version }}.jar
        tag: "${{ github.ref }}"
        overwrite: true
        body: "Executable ConverSyDe Crossplatform Jar"
    - name: Upload Bundle to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: conversyde.zip
        asset_name: conversyde-linux-${{ steps.get_version.outputs.version }}.zip
        tag: "${{ github.ref }}"
        overwrite: true
        body: "Executable ConverSyDe Linux"
  publish-conversyde-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Build with Gradle (All)
        # if: ${{ matrix.os != 'windows-latest' }}
        run: |
          cd ${{ github.workspace }}
          .\gradlew jar shadowJar java-conversyde:jpackageImage
      - name: Zipping the image files
        run: |
          cd ${{ github.workspace }}/java-conversyde/build/jpackage
          zip -q -r conversyde.zip java-conversyde/*
      - name: Upload Bundle to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/java-conversyde/build/jpackage/conversyde.zip
          asset_name: conversyde-windows-${{ steps.get_version.outputs.version }}.jar
          tag: "${{ github.ref }}"
          overwrite: true
          body: "Executable ConverSyDe Windows"
