# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name:  Released Java Supporting Libraries

on:
  release:
    types: [created]

env:
    MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
    MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
    USERNAME: ${{ github.actor }}
    TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy-java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.11
        server-id: io.github.forsyde # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - id: localVersion
      name: Retrieve lib version
      run: |
        cd ${{ github.workspace }}
        echo "localVersion=$(./gradlew getVersion)" >> $GITHUB_ENV
        echo "Version saved: $GITHUB_ENV"
    - name: Build and publish with Gradle
      if: ${{ steps.get_version.outputs.version-without-v == env.localVersion }}
      run: |
        cd ${{ github.workspace }}
        ./gradlew build publish closeAndReleaseSonatypeStagingRepository