# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test Building Supporting Libraries

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  test-build-python:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.7, 3.8, 3.9]
        poetry: [1.1.5]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under ${{ github.workspace }}, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python }}'
      - uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: '${{ matrix.poetry }}'

      # Runs a set of commands using the runners shell
      - name: Generate lib
        run: |
          cd ${{ github.workspace }}
          poetry update
          poetry run generate
      - name: Build lib
        run: |
          cd ${{ github.workspace }}/python
          poetry update
          poetry install
  test-java-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.7, 3.8, 3.9]
        java: [1.8]
        poetry: [1.1.5]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1.4.3
      with:
        java-version: ${{ matrix.java }}
        server-id: io.github.forsyde # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '${{ matrix.python }}'
    - uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: '${{ matrix.poetry }}'
    - name: generate additional code for supporting libs
      run: |
        cd ${{ github.workspace }}
        poetry update
        poetry run generate
    - name: Build with Gradle (Unix)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        cd ${{ github.workspace }}/java
        ./gradlew build
    - name: Build with Gradle (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        cd ${{ github.workspace }}\java
        .\gradlew.bat build

